version: '3.8'

services:
  # 1. Database: SQL Server
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: simsimi-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Sa@123456 # Đã thêm 456 để đủ 9 ký tự
    ports:
      - "1433:1433"
    networks:
      - simsimi-network
    volumes:
      - sql_data_v2:/var/opt/mssql # Đổi tên volume để reset lại DB

  # 2. Backend: C# ASP.NET Core
  backend:
    build:
      context: ./SimsimiChat
      dockerfile: Dockerfile
    container_name: simsimi-backend
    ports:
      - "5000:8080" # Máy khách gọi cổng 5000, Docker đẩy vào 8080 của App
    environment:
      # Passowrd ở đây phải khớp 100% với password của db ở trên
      - ConnectionStrings__DefaultConnection=Server=db;Database=SimsimiDb;User Id=sa;Password=Sa@123456;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080 # Ép C# mở cửa đúng cổng 8080 bên trong Docker
    depends_on:
      - db
    networks:
      - simsimi-network

  # 3. Frontend: ReactJS (Vite)
  frontend:
    build:
      context: ./simsimiFE
      dockerfile: Dockerfile
    container_name: simsimi-frontend
    ports:
      - "3000:80" # Truy cập web qua cổng 3000
    depends_on:
      - backend
    networks:
      - simsimi-network

networks:
  simsimi-network:
    driver: bridge

volumes:
  sql_data_v2: # Nhớ đổi tên ở dưới cùng này nữa